Added in missing cost basis and fixed column mismatch.
RichardMcSorley/M1-Export-Chrome-Extension pull request #2
Opened 2020-09-11 05:48 UTC by patrick-motard

Fixes #1 

M1's holding tab:
<img width="1181" alt="Screen Shot 2020-09-11 at 12 32 25 AM" src="https://user-images.githubusercontent.com/6657259/92867970-d7ee1500-f3c6-11ea-8bca-03f6304b9762.png">

Current behavior:
<img width="923" alt="Screen Shot 2020-09-11 at 12 33 36 AM" src="https://user-images.githubusercontent.com/6657259/92868019-e63c3100-f3c6-11ea-9183-ec5603b70c50.png">

Behavior from this PR:
<img width="923" alt="Screen Shot 2020-09-11 at 12 35 33 AM" src="https://user-images.githubusercontent.com/6657259/92868063-f0f6c600-f3c6-11ea-947b-09c98612e491.png">

- The 'Cost Basis' column wasn't present. It has been added.
- 'Maintenance' has been removed because it's not useful.
- 'Value' now correctly shows value.
- 'Unrealized Gain' and 'Unrealized Gain%' fixed to show correct values.

NOTE: This PR might cause issues with simply safe dividends. Based on the following comment in code:
```
        // First 3 lines  should not move, the order is to support simply safe dividends
```
If the first three values need to be names, shares, and price so that the data can be exported to simply safe, that would no longer work, because this PR sets the column order to match the column order in M1 Finance. I'd suggest that if we need to support Simply Safe, we add a 3rd/4th option that says 'Copy 'Simply Safe Compatible' to clipboard' and 'Save 'Simply Safe Compatible' to CSV'.

2020-09-12 00:47 UTC, RichardMcSorley requested changes
We can go with this solution, I like your idea of making it a separate option for simply safe dividends. 

I ask either keep the headers and return array in the same order for the first 3 items in the arrays or remove the comments on the line before those two arrays.

2020-09-12 05:07 UTC, patrick-motard commented
Thanks for the review. I'll have time to address this early next week. I'll add the context for Simply Safe as well.

2020-09-16 03:50 UTC, patrick-motard commented
@RichardMcSorley I've added a commit that addresses your initial review:
- comments about simply safe removed from `getData()`
- context menu now allows copy or save to csv in either the native m1 format, or simply safe format

2020-11-19 16:09 UTC, patrick-motard commented
bump

2020-11-20 23:26 UTC, RichardMcSorley approved these changes

2020-11-20 23:26 UTC, merged

2020-11-20 23:27 UTC, RichardMcSorley commented
@patrick-motard Thanks for the contribution. I apologize for not getting back to you until now.

2020-11-20 23:36 UTC, RichardMcSorley commented
I've bumped the version to 1.3 and it will undergo review from Google usually within 24 hours.